language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - PLUGIN_NAME=Tags
    - REQUIRE="phpunit/phpunit:6.3.0"
    - DB=mysql CAKE_VERSION=master


  matrix:
    - DB=mysql CAKE_VERSION=master

matrix:
  include:
    - php: 5.6
      env:
        - CAKE_VERSION=master
    - php: 7.0
      env:
        - CAKE_VERSION=master
    - php: 7.1
      env:
        - CAKE_VERSION=master

before_script:
  - cp -R tags ../tags && cd ../tags
  - ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
