language: php

php:
  - 5.6

env:
  global:
    - PLUGIN_NAME=Tags
    - REQUIRE=""
    - DB=mysql CAKE_VERSION=3.4

  matrix:
    - DB=mysql CAKE_VERSION=3.4

matrix:
  include:
    - php: 5.6
      env:
        - PHPCS=1

before_script:
  - ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
